In [1]:
import pandas as pd
import networkx as nx
import numpy as np
from scipy.stats import zscore

In [2]:
rnaseq_data = pd.read_csv("D://CCLE_data/CCLE/CCLE_RNAseq_rsem_genes_tpm_20180929.txt/CCLE_RNAseq_rsem_genes_tpm_20180929.txt", sep = "\t")

In [3]:
rnaseq_columns = []
for item in rnaseq_data.columns:
    item = item.split("_")[0]
    rnaseq_columns.append(item)
    
rnaseq_data.columns = rnaseq_columns
rnaseq_data = rnaseq_data.set_index("gene")

In [4]:
import mygene

In [5]:
geneids = rnaseq_data.index.tolist()
geneids = [i.split(".")[0] for i in geneids]
geneids_test = geneids[:20]
rnaseq_data.index = geneids

In [6]:
mg = mygene.MyGeneInfo()
gene_symbols = mg.querymany(geneids, scopes='ensembl.gene', species = "human", fields = "symbol", returnall = False, as_dataframe = True)

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-17000...done.
querying 17001-18000...done.
querying 18001-19000...done.
querying 19001-20000...done.
querying 20001-21000...done.
querying 21001-22000...done.
querying 22001-23000...done.
querying 23001-24000...done.
querying 24001-25000...done.
querying 25001-26000...done.
querying 26001-27000...done.
querying 27001-28000...done.
querying 28001-29000...done.
querying 29001-30000...done.
querying 30001-31000...done.
querying 31001-32000...done.
querying 32001-33000...done.
querying 33001-34000...done.
querying 34001-35000...done.
querying 35001-36000...done.
querying 36001-37000...done.
querying 37001-38000...done.
querying 38001-39000...done.
querying 39001-40000...done.
querying 40001-41000...done.
querying 41001-42000...done.
querying 42001-43000...done.
querying 43001-44000...done.
querying 44001-45000...done.
querying 45001-46000...done.
querying 46001-47000...done.
querying 47001-48000...done.
querying 48001-49000...done.
querying 49001-50000...done.
querying 50001-51000...done.
querying 51001-52000...done.
querying 52001-53000...done.
querying 53001-54000...done.
querying 54001-55000...done.
querying 55001-56000...done.
querying 56001-57000...done.
querying 57001-57820...done.
Finished.

C:\Users\ds728\anaconda3\lib\site-packages\biothings_client\base.py:143: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  df = json_normalize(obj)

2 input query terms found dup hits:
	[('ENSG00000229425', 2), ('ENSG00000249981', 2)]
5714 input query terms found no hit:
	['ENSG00000005955', 'ENSG00000006074', 'ENSG00000006075', 'ENSG00000006114', 'ENSG00000017373', 'ENS
Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [7]:
gene_symbols_found = gene_symbols[gene_symbols["notfound"] != True]
gene_symbols_found = gene_symbols_found[["_id", "symbol"]]

In [25]:
combined_data = rnaseq_data.merge(gene_symbols_found, left_index = True, right_index = True)
combined_data = combined_data.drop("_id", axis =1)
combined_data = combined_data.drop("transcript", axis =1)
combined_data = combined_data.drop_duplicates(subset = "symbol")
combined_data =combined_data.set_index("symbol")

In [26]:
combined_data

,22RV1,2313287,253JBV,253J,42MGBA,5637,59M,639V,647V,697,...,WSUDLCL2,YAPC,YD10B,YD15,YD38,YD8,YH13,YKG1,ZR751,ZR7530
symbol,,,,,,,,,,,,,,,,,,,,,
TSPAN6,5.28,7.01,22.80,22.88,23.09,57.94,16.30,32.02,60.53,0.11,...,0.74,50.29,14.18,24.13,20.94,47.96,28.92,61.08,8.12,16.81
TNMD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
DPM1,73.38,108.99,56.51,45.39,99.28,98.95,79.68,125.99,89.59,43.03,...,41.71,103.70,97.07,104.97,96.86,119.50,64.09,109.13,139.23,56.20
SCYL3,9.76,16.76,2.58,3.25,2.73,3.11,2.69,2.69,2.83,4.19,...,5.60,7.76,2.96,5.84,4.17,5.06,4.94,5.91,15.96,13.76
C1orf112,24.51,13.32,10.86,5.26,9.27,31.61,9.62,10.45,15.90,19.54,...,20.21,12.84,11.38,14.58,22.13,9.58,13.35,17.40,17.45,11.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LINC02725,0.03,0.32,0.00,0.00,0.00,0.54,0.02,0.03,0.08,0.00,...,0.00,0.09,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
OR13I1P,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00
OR8S21P,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
OR6R2P,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
APP-DT,0.01,0.08,0.10,0.35,0.01,0.06,0.00,0.11,0.00,0.06,...,0.00,0.04,0.00,0.00,0.02,0.00,0.00,0.07,0.02,0.11

In [27]:
celllines_mapped = pd.read_csv("../MCF7_removal/Celllines_mapping_manual_noMCF7.csv")
# Get only cell lines with ID
celllines_mapped = celllines_mapped.drop_duplicates(subset = ["dsIdx"])
celllines_mapped = celllines_mapped.dropna(subset = ["ID"])
sample_data_tissue = celllines_mapped["DI"].tolist()

celllines_replaced = []
for item in sample_data_tissue:
    item = item.replace("-", "")
    item = item.replace(".", "")
    item = item.replace(" ", "")
    item = item.split("[")[0]
    item = item.upper()
    celllines_replaced.append(item)

In [28]:
metabolomics_data = pd.read_csv("../MCF7_removal/Metabolomics_data_noMCF7.csv", index_col = "ionIdx")

In [29]:
metabolomics_data = metabolomics_data.drop("ionMz", axis =1)

In [30]:
average_celllines = []

for item in celllines_mapped["ID"].unique():
    ids = celllines_mapped[celllines_mapped["ID"] == item]["dsIdx"].tolist()
    ids = [str(i) for i in ids] 
    metabolomics_data_subset = metabolomics_data[ids]
    metabolomics_data_subset[item] = metabolomics_data_subset.mean(axis =1)
    average_df = metabolomics_data_subset[item]
    average_celllines.append(average_df)

C:\Users\ds728\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [31]:
averaged_metabolites = pd.concat(average_celllines, axis =1)

In [32]:
updated_columns = []
for item in averaged_metabolites.columns:
    item = item.replace("-", "")
    item = item.replace(".", "")
    item = item.replace(" ", "")
    item = item.split("[")[0]
    item = item.upper()
    updated_columns.append(item)
    
averaged_metabolites.columns = updated_columns

In [33]:
averaged_metabolites

,SHP77,PC9,LUDLU1,PC14PE6,NCIH446,MALME3M,NCIH1755,NCIH2135,HCC1187,CORL88,...,NCIH146,HL60,NCIH82,SF268,SF539,CCRFCEM,K562,DU4475,UO31,EKVX
ionIdx,,,,,,,,,,,,,,,,,,,,,
1,8465.333333,9022.333333,8837.75,7749.833333,9303.2,8096.666667,9522.833333,9311.833333,10228.5,7732.750000,...,8740.333333,6372.666667,7893.000000,6933.333333,6384.333333,7557.833333,8142.166667,7113.666667,7287.666667,7237.500000
2,4044.666667,4554.500000,2194.00,2352.666667,5165.7,1998.833333,2083.500000,4409.666667,3315.6,5039.000000,...,3292.833333,1815.833333,1601.000000,2503.833333,1782.333333,1780.000000,1496.666667,859.833333,2329.666667,2441.166667
3,64033.500000,83264.666667,62600.00,51762.333333,82707.7,64092.500000,80059.500000,109218.500000,98461.9,57604.833333,...,38132.333333,40767.333333,38523.500000,65668.333333,76605.666667,53527.333333,42010.500000,35301.666667,35755.333333,49048.666667
4,4723.000000,5952.500000,4993.75,4581.333333,5605.3,4952.000000,5956.500000,6275.166667,6132.9,4296.750000,...,4892.166667,4106.000000,3986.833333,5752.666667,6547.166667,5084.666667,4754.833333,5805.333333,4156.666667,4145.833333
5,4695.166667,9180.833333,5782.25,5874.000000,4996.0,4073.333333,5541.000000,5095.666667,5776.9,5652.500000,...,3167.666667,3275.666667,3918.500000,3891.500000,3358.666667,5203.666667,3115.833333,2953.000000,3919.166667,3034.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,2930.000000,2542.000000,5661.75,3271.666667,3697.1,4537.000000,2824.666667,2506.500000,2943.1,2508.500000,...,3389.666667,1732.333333,3628.833333,1996.166667,1661.833333,1680.333333,3609.333333,3260.000000,1794.000000,3022.666667
1096,-337.166667,-42.166667,675.25,527.000000,453.1,597.500000,482.000000,612.666667,496.0,-52.250000,...,2042.833333,1868.166667,2737.833333,230.166667,1751.333333,2548.000000,1441.833333,1126.666667,894.833333,87.666667
1097,1532.666667,1109.166667,2173.25,1529.333333,1179.9,922.833333,1642.333333,685.000000,725.0,1635.666667,...,851.500000,378.000000,196.500000,603.000000,152.500000,189.166667,397.333333,252.500000,218.166667,978.333333
1098,1191.666667,1577.500000,2584.50,2158.666667,2382.1,2272.666667,1954.500000,1397.166667,2186.2,1654.000000,...,2806.500000,2226.666667,3140.833333,1265.833333,986.833333,2221.333333,3037.500000,2767.000000,1442.333333,987.666667
1099,1869.333333,1665.000000,2180.25,2541.000000,2551.0,2482.666667,2280.666667,2135.333333,2076.0,1674.500000,...,2302.000000,1677.333333,2949.500000,1302.000000,1038.000000,1197.333333,3118.666667,2594.166667,1440.166667,1476.666667

In [34]:
metabolites_rnaseq_combined = pd.concat([averaged_metabolites, combined_data], join = "inner")

In [35]:
metabolites_rnaseq_combined

,SHP77,PC9,LUDLU1,NCIH446,MALME3M,NCIH1755,HCC1187,CORL88,NCIH2171,NCIH1155,...,NCIH526,NCIH146,HL60,NCIH82,SF268,SF539,K562,DU4475,UO31,EKVX
1,8465.333333,9022.333333,8837.75,9303.20,8096.666667,9522.833333,10228.50,7732.750000,7543.50,6046.50,...,6952.333333,8740.333333,6372.666667,7893.000000,6933.333333,6384.333333,8142.166667,7113.666667,7287.666667,7237.500000
2,4044.666667,4554.500000,2194.00,5165.70,1998.833333,2083.500000,3315.60,5039.000000,1649.50,1921.75,...,3126.833333,3292.833333,1815.833333,1601.000000,2503.833333,1782.333333,1496.666667,859.833333,2329.666667,2441.166667
3,64033.500000,83264.666667,62600.00,82707.70,64092.500000,80059.500000,98461.90,57604.833333,56346.50,92005.00,...,43897.833333,38132.333333,40767.333333,38523.500000,65668.333333,76605.666667,42010.500000,35301.666667,35755.333333,49048.666667
4,4723.000000,5952.500000,4993.75,5605.30,4952.000000,5956.500000,6132.90,4296.750000,4957.25,6419.50,...,5052.000000,4892.166667,4106.000000,3986.833333,5752.666667,6547.166667,4754.833333,5805.333333,4156.666667,4145.833333
5,4695.166667,9180.833333,5782.25,4996.00,4073.333333,5541.000000,5776.90,5652.500000,4796.50,1272.00,...,4355.833333,3167.666667,3275.666667,3918.500000,3891.500000,3358.666667,3115.833333,2953.000000,3919.166667,3034.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LINC02725,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.06,0.040000,0.00,0.00,...,2.050000,0.190000,0.000000,0.000000,0.060000,0.090000,0.000000,0.000000,0.000000,0.050000
OR13I1P,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.00,0.000000,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020000,0.000000,0.000000
OR8S21P,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.00,0.000000,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
OR6R2P,0.000000,0.000000,0.00,0.00,0.000000,0.000000,0.00,0.000000,0.00,0.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
APP-DT,0.010000,0.040000,0.00,0.05,0.020000,0.010000,0.32,0.150000,0.10,0.01,...,0.140000,0.060000,0.000000,0.010000,0.030000,0.040000,0.000000,0.950000,0.830000,0.070000

In [36]:
metabolites_rnaseq_combined.to_csv("metabolite_rnaseq_correlation_matrix.csv")